services:
  - type: web
    name: medisync-backend
    env: docker
    dockerContext: ./backend
    dockerfilePath: Dockerfile
    plan: free
    region: singapore
    healthCheckPath: /api/auth/health
    envVars:
      - key: DB_URL
        value: jdbc:h2:mem:medisync_db;MODE=MySQL;DB_CLOSE_DELAY=-1
      - key: DB_USER
        value: sa
      - key: DB_PASSWORD
        value: password
      - key: JWT_SECRET
        value: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - key: GROQ_API_KEY
        value: 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
      - key: SERVER_PORT
        value: "8080"
