#!/usr/bin/expect -f
set timeout -1
set password "PVYZKN@etxcm588"
set ip "164.52.213.234"

spawn ssh -o StrictHostKeyChecking=no root@$ip "ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default && nginx -t && systemctl reload nginx && certbot install --cert-name medisync-hospital.duckdns.org --nginx --non-interactive --redirect"
expect {
    "*password:*" {
        send "$password\r"
    }
}
interact
