#!/usr/bin/expect -f
set timeout -1
set password "PVYZKN@etxcm588"
set ip "164.52.213.234"
set domain "medisync-hospital.duckdns.org"

spawn ssh -o StrictHostKeyChecking=no root@$ip "sed -i 's|/etc/ssl/certs/medisync.crt|/etc/letsencrypt/live/$domain/fullchain.pem|g' /etc/nginx/sites-available/default && sed -i 's|/etc/ssl/private/medisync.key|/etc/letsencrypt/live/$domain/privkey.pem|g' /etc/nginx/sites-available/default && nginx -t && systemctl reload nginx"
expect {
    "*password:*" {
        send "$password\r"
    }
}
interact
