#!/usr/bin/expect -f
set timeout -1
set password "PVYZKN@etxcm588"
set ip "164.52.213.234"

spawn scp -o StrictHostKeyChecking=no scratch/upgrade_to_https.sh root@$ip:~/
expect {
    "*password:*" {
        send "$password\r"
    }
}
expect eof

spawn ssh -o StrictHostKeyChecking=no root@$ip "chmod +x ~/upgrade_to_https.sh && ./upgrade_to_https.sh"
expect {
    "*password:*" {
        send "$password\r"
    }
}
interact
