#!/usr/bin/expect -f
set timeout -1
set password "PVYZKN@etxcm588"
set ip "164.52.213.234"

spawn ssh -o StrictHostKeyChecking=no root@$ip "rm -f /etc/nginx/sites-enabled/medisync && certbot --nginx -d medisync-hospital.duckdns.org -d medisync-hos.ddns.net --non-interactive --agree-tos --register-unsafely-without-email --redirect && systemctl restart nginx"
expect {
    "*password:*" {
        send "$password\r"
    }
}
interact
