#!/usr/bin/expect -f
set timeout 600
set password "PVYZKN@etxcm588"
spawn ssh -o StrictHostKeyChecking=no root@164.52.213.234
expect "password:"
send "$password\r"
expect "root@*"
send "apt-get update && apt-get install -y redis-server\r"
expect "root@*"
send "systemctl enable redis-server && systemctl start redis-server\r"
expect "root@*"
send "redis-cli ping\r"
expect "PONG"
send "exit\r"
expect eof
